"""Tier 2 chapters: brass Create, Mekanism intro, storage, kitchen."""
from lib import register_chapter, I, K, CK, R, XP, LV

T2 = 0x30000

# ── t2_create_brass ──────────────────────────────────────────────────────────
register_chapter("t2_create_brass", 0x31000, T2, 0, "The Brass Age", "create:brass_casing", [
    dict(n=1, title="Blaze Burner", icon="create:blaze_burner", x=0.0, y=0.0,
         sub="Pet fire demon. Do not feed after midnight. Do feed constantly otherwise.",
         deps=[("t1_create", 11), ("t1_survival", 14)],
         desc=["Right-click a Blaze with an empty Blaze Burner to capture it. Yes, really.",
               "Place it under a Basin and feed it fuel — now your Mixer can smelt. This unlocks brass."],
         tasks=[I("create:blaze_burner")],
         rewards=[R("minecraft:coal_block", 4), XP(150)]),
    dict(n=2, title="Brass!", icon="create:brass_ingot", x=1.5, y=0.0,
         sub="Copper plus zinc plus fire equals progress.", deps=[1],
         desc=["Mix copper and zinc in a heated Basin (Blaze Burner below, Mixer above) to create brass.",
               "Brass is THE Tier 2 material. Automate it immediately — you need stacks."],
         tasks=[I("create:brass_ingot", 16)],
         rewards=[R("create:zinc_ingot", 16), R("minecraft:copper_ingot", 16), XP(150)]),
    dict(n=3, title="Brass Casing", icon="create:brass_casing", x=3.0, y=0.0,
         sub="Now in gold-ish.", deps=[2],
         desc=["Brass Casings unlock the smart side of Create: precise machines, smart funnels and complex automation."],
         tasks=[I("create:brass_casing", 8)],
         rewards=[R("create:brass_ingot", 16), XP(150)]),
    dict(n=4, title="Electron Tubes", icon="create:electron_tube", x=3.0, y=1.5,
         sub="Polished rose quartz, now with opinions.", deps=[3],
         desc=["Sand rose quartz on a grindstone or with a belt sander setup, then combine for Electron Tubes.",
               "These little circuits go into every advanced Create machine."],
         tasks=[I("create:electron_tube", 8)],
         rewards=[R("minecraft:redstone", 32), XP(125)]),
    dict(n=5, title="Mechanical Crafter", icon="create:mechanical_crafter", x=4.5, y=0.0,
         sub="A 3x3 grid with commitment issues.", deps=[3, 4],
         desc=["Mechanical Crafters chain together into custom crafting grids that run automatically.",
               "You need a 3x3 of them for some of our custom recipes — including the Resource Catalyst later!"],
         tasks=[I("create:mechanical_crafter", 9)],
         rewards=[R("create:brass_casing", 8), XP(200)]),
    dict(n=6, title="Precision Mechanism", icon="create:precision_mechanism", x=6.0, y=0.0,
         sub="Fiddly. Worth it.", deps=[5],
         desc=["The Precision Mechanism is crafted in stages on a Depot with a Deployer — Ponder it to see the dance.",
               "This component gates almost all advanced tech in this pack. Automate it and prosper."],
         tasks=[I("create:precision_mechanism", 4)],
         rewards=[R("create:precision_mechanism", 2), LV(5)]),
    dict(n=7, title="Mechanical Arm", icon="create:mechanical_arm", x=7.5, y=0.0,
         sub="You, but automated.", deps=[6],
         desc=["The Mechanical Arm moves items between any inputs and outputs you select with it before placing.",
               "The final piece of Create logistics. Your factory is now officially smarter than you."],
         tasks=[I("create:mechanical_arm")],
         rewards=[R("create:brass_hand"), LV(5)]),
    dict(n=8, title="Smart Sorting", icon="create:brass_funnel", x=4.5, y=1.5,
         sub="Tunnel vision, the good kind.", deps=[3], optional=True, shape="diamond",
         desc=["Brass Funnels filter what they pick up. Brass Tunnels split items across parallel belts and balance entire systems.",
               "Build a sorted storage wall and feel the serenity."],
         tasks=[I("create:brass_funnel", 4), I("create:brass_tunnel", 4)],
         rewards=[R("create:filter", 8), XP(150)]),
    dict(n=9, title="All Aboard!", icon="create:track", x=6.0, y=1.5,
         sub="Choo choo, but mechanical.", deps=[3], optional=True, shape="diamond",
         desc=["Create has full train support — lay tracks, assemble a train with a Train Station, set up schedules.",
               "Steam 'n' Rails adds even more: conductors, switches and track types. Connect your bases in style!"],
         tasks=[I("create:track", 16), I("create:train_station")],
         rewards=[R("create:track", 32), R("create:schedule"), LV(5)]),
    dict(n=10, title="The Deployer", icon="create:deployer", x=7.5, y=1.5,
         sub="A hand on a stick. Surprisingly versatile.", deps=[6], optional=True, shape="diamond",
         desc=["Deployers place blocks, use tools, plant crops and click things — anything you can do, on repeat, forever.",
               "Essential for Precision Mechanism automation."],
         tasks=[I("create:deployer", 2)],
         rewards=[R("create:electron_tube", 8), XP(150)]),
])

# ── t2_mekanism ──────────────────────────────────────────────────────────────
register_chapter("t2_mekanism", 0x32000, T2, 1, "Green Machines", "mekanism:metallurgic_infuser", [
    dict(n=1, title="Osmium — The New Iron", icon="mekanism:ingot_osmium", x=0.0, y=0.0,
         sub="Heavier. Bluer. Better.",
         deps=[("t1_survival", 7)],
         desc=["Osmium is Mekanism's foundation metal, found underground everywhere.",
               "Tip: our custom Crushed Osmium from Create crushing wheels smelts into ingots too."],
         tasks=[I("mekanism:ingot_osmium", 16)],
         rewards=[R("mekanism:ingot_osmium", 8), XP(100)]),
    dict(n=2, title="Metallurgic Infuser", icon="mekanism:metallurgic_infuser", x=1.5, y=0.0,
         sub="The machine that makes the machines.", deps=[1],
         desc=["The Metallurgic Infuser combines materials with infusion types: redstone, carbon, diamond.",
               "It crafts Infused Alloys and Steel — the ingredients of every other Mekanism machine."],
         tasks=[I("mekanism:metallurgic_infuser")],
         rewards=[R("mekanism:alloy_infused", 8), XP(150)]),
    dict(n=3, title="Steel Yourself", icon="mekanism:ingot_steel", x=3.0, y=0.0,
         sub="Iron, but it went to the gym.", deps=[2],
         desc=["Infuse iron with carbon twice (via Enriched Carbon) to make steel.",
               "Steel Casings are the chassis of all Mekanism machines — stock up."],
         tasks=[I("mekanism:ingot_steel", 16)],
         rewards=[R("minecraft:iron_ingot", 32), XP(150)]),
    dict(n=4, title="Enrichment Chamber", icon="mekanism:enrichment_chamber", x=4.5, y=0.0,
         sub="Ores go in. MORE comes out.", deps=[3, ("t2_create_brass", 6)],
         desc=["The Enrichment Chamber doubles ores into dust and enriches materials for infusion.",
               "Combined with an Energized Smelter or furnace, this is reliable x2 ore processing."],
         tasks=[I("mekanism:enrichment_chamber")],
         rewards=[R("mekanism:basic_control_circuit", 4), XP(200)]),
    dict(n=5, title="The x2 Ore Chain", icon="mekanism:dust_iron", x=6.0, y=0.0,
         sub="Twice the metal, none of the guilt.", deps=[4],
         desc=["Run your raw ores through the Enrichment Chamber and smelt the dust.",
               "Later tiers add Purification (x3) and Chemical Injection (x4) — this is just the beginning."],
         tasks=[I("mekanism:dust_iron", 32)],
         rewards=[R("minecraft:raw_gold", 24), XP(150)]),
    dict(n=6, title="Stored Energy", icon="mekanism:basic_energy_cube", x=7.5, y=0.0,
         sub="A battery the size of your ambitions.", deps=[4],
         desc=["Mekanism machines run on Forge Energy. The Basic Energy Cube stores it and shares it.",
               "Power it from Create Crafts and Additions generators — more on that in Tier 3."],
         tasks=[I("mekanism:basic_energy_cube")],
         rewards=[R("mekanism:alloy_infused", 8), XP(150)]),
    dict(n=7, title="Heat Generator", icon="mekanismgenerators:heat_generator", x=6.0, y=1.5,
         sub="Lava-powered and proud.", deps=[3], optional=True, shape="diamond",
         desc=["The Heat Generator burns fuel or passively converts adjacent lava into power.",
               "Surround it with lava for free trickle energy — perfect for your first machines."],
         tasks=[I("mekanismgenerators:heat_generator")],
         rewards=[R("minecraft:lava_bucket"), XP(125)]),
    dict(n=8, title="Tanks for Everything", icon="mekanism:basic_fluid_tank", x=4.5, y=1.5,
         sub="It holds liquid. Revolutionary.", deps=[3], optional=True, shape="diamond",
         desc=["Mekanism fluid tanks stack their capacity when upgraded and work as portable buckets in your hand.",
               "Sneak-right-click to toggle bucket mode."],
         tasks=[I("mekanism:basic_fluid_tank")],
         rewards=[R("minecraft:bucket", 4), XP(100)]),
    dict(n=9, title="The Configurator", icon="mekanism:configurator", x=3.0, y=1.5,
         sub="The Swiss Army wrench.", deps=[2], optional=True, shape="diamond",
         desc=["The Configurator sets machine sides: input here, output there, eject automatically.",
               "Master it and your machines chain together without any pipes at all."],
         tasks=[I("mekanism:configurator")],
         rewards=[R("mekanism:ingot_osmium", 8), XP(100)]),
])

# ── t2_storage ───────────────────────────────────────────────────────────────
register_chapter("t2_storage", 0x33000, T2, 2, "Stay Organized", "functionalstorage:storage_controller", [
    dict(n=1, title="Drawers", icon="functionalstorage:oak_2", x=0.0, y=0.0,
         sub="One item type, thousands of them.",
         deps=[("t1_survival", 7)],
         desc=["Functional Storage drawers hold huge amounts of a single item — perfect for cobble, ingots and crops.",
               "Double-click to deposit all matching items from your inventory."],
         tasks=[I("functionalstorage:oak_2", 4)],
         rewards=[R("functionalstorage:oak_4", 2), XP(100)]),
    dict(n=2, title="Storage Controller", icon="functionalstorage:storage_controller", x=1.5, y=0.0,
         sub="One block to rule them all.", deps=[1],
         desc=["Link your drawer wall to a Storage Controller and interact with ALL drawers through one block.",
               "Throw items at it. Seriously, just throw them — it sorts everything in."],
         tasks=[I("functionalstorage:storage_controller")],
         rewards=[R("functionalstorage:oak_4", 4), XP(150)]),
    dict(n=3, title="Sophisticated Storage", icon="minecraft:chest", x=3.0, y=0.0,
         sub="Chests with a college degree.", deps=[1],
         desc=["Sophisticated Storage chests and barrels take the same upgrades as the backpacks: stack upgrades, auto-smelting, even compacting.",
               "Upgrade tiers multiply capacity — a netherite chest holds a small warehouse."],
         tasks=[CK("Craft and upgrade a Sophisticated chest or barrel")],
         rewards=[R("minecraft:diamond", 4), XP(150)]),
    dict(n=4, title="Magnet Time", icon="simplemagnets:basicmagnet", x=1.5, y=1.5,
         sub="Items come to YOU now.", deps=[1], optional=True, shape="diamond",
         desc=["The Simple Magnet pulls dropped items toward you. Toggle it with a keybind.",
               "Combined with your backpack magnet upgrade, nothing touches the floor ever again."],
         tasks=[I("simplemagnets:basicmagnet")],
         rewards=[R("minecraft:gold_ingot", 8), XP(100)]),
    dict(n=5, title="Just Carry It", icon="minecraft:shulker_box", x=3.0, y=1.5,
         sub="Gym membership finally pays off.", deps=[3], optional=True, shape="diamond",
         desc=["Carry On lets you pick up chests, machines — even mobs — by sneak-right-clicking with an empty hand.",
               "Relocate your whole base without breaking a single block."],
         tasks=[CK("Carry a block or mob with Carry On")],
         rewards=[R("minecraft:ender_chest"), XP(100)]),
])

# ── t2_kitchen ───────────────────────────────────────────────────────────────
register_chapter("t2_kitchen", 0x34000, T2, 3, "Chef's Table", "farmersdelight:iron_knife", [
    dict(n=1, title="Sharp Knife, Sharp Mind", icon="farmersdelight:iron_knife", x=0.0, y=0.0,
         sub="Cutting-edge technology.",
         deps=[("t1_survival", 5)],
         desc=["The knife harvests crops gently and cuts ingredients on the Cutting Board for extra portions.",
               "Knife plus Cutting Board equals double the food from the same harvest."],
         tasks=[I("farmersdelight:iron_knife"), I("farmersdelight:cutting_board")],
         rewards=[R("minecraft:emerald", 4), XP(100)]),
    dict(n=2, title="Rich Soil", icon="farmersdelight:rich_soil", x=1.5, y=0.0,
         sub="Dirt, deluxe edition.", deps=[1],
         desc=["Rich Soil accelerates crop growth and never needs re-tilling. Compost organic material to make it.",
               "Your Mystical Agriculture farm will thank you later."],
         tasks=[I("farmersdelight:rich_soil", 16)],
         rewards=[R("minecraft:bone_block", 8), XP(125)]),
    dict(n=3, title="Feast Mode", icon="farmersdelight:cooking_pot", x=3.0, y=0.0,
         sub="Saturation is a love language.", deps=[1], optional=True, shape="diamond",
         desc=["Cook a proper multi-ingredient meal in the Cooking Pot. Big meals give Nourishment — passive saturation regen.",
               "Feed your whole team before a boss fight. Trust the buff."],
         tasks=[CK("Cook a meal in the Cooking Pot")],
         rewards=[R("minecraft:golden_carrot", 16), R("minecraft:cake", 2), XP(150)]),
])
