"""Tier 3 chapters: AE2, power generation, PneumaticCraft, Mystical Agriculture, magic."""
from lib import register_chapter, I, K, CK, R, XP, LV

T3 = 0x40000

# ── t3_power ─────────────────────────────────────────────────────────────────
register_chapter("t3_power", 0x41000, T3, 0, "Power Up", "createaddition:electric_motor", [
    dict(n=1, title="Rotation Becomes Power", icon="createaddition:alternator", x=0.0, y=0.0,
         sub="Spin me right round.",
         deps=[("t2_create_brass", 6), ("t2_mekanism", 6)],
         desc=["Create Crafts and Additions bridges the two worlds: the Alternator turns Create rotation into Forge Energy.",
               "Hook it to your windmill or water wheels and watch the FE flow."],
         tasks=[I("createaddition:alternator")],
         rewards=[R("createaddition:electric_motor"), XP(150)]),
    dict(n=2, title="Electric Motor", icon="createaddition:electric_motor", x=1.5, y=0.0,
         sub="And back again.", deps=[1],
         desc=["The Electric Motor does the reverse: FE in, rotation out. Compact, adjustable, no blaze required.",
               "Together with the Alternator you can route power anywhere as electricity."],
         tasks=[I("createaddition:electric_motor")],
         rewards=[R("minecraft:copper_block", 4), XP(150)]),
    dict(n=3, title="Powah Unlocked", icon="powah:furnator_basic", x=3.0, y=0.0,
         sub="It generates. It just works.", deps=[2],
         desc=["Powah adds dedicated FE generators: Furnators burn fuel, Thermo Generators sit on heat sources, Solar Panels love the sun.",
               "Cheap, scalable and upgradeable through six tiers."],
         tasks=[I("powah:furnator_basic")],
         rewards=[R("powah:thermo_generator_basic"), XP(150)]),
    dict(n=4, title="Energy Storage", icon="powah:battery_basic", x=4.5, y=0.0,
         sub="Save it for a rainy day.", deps=[3],
         desc=["Batteries buffer your power so machines never starve during demand spikes.",
               "Energy Cells, Energy Cubes, Accumulators — pick your flavor, but have a buffer."],
         tasks=[I("powah:battery_basic")],
         rewards=[R("mekanism:basic_energy_cube"), XP(200)]),
    dict(n=5, title="XNet — The Nervous System", icon="xnet:controller", x=6.0, y=0.0,
         sub="One cable. Everything. Everywhere.", deps=[4],
         desc=["XNet routes items, fluids AND energy through a single cable network with per-connector rules.",
               "One controller can manage your entire base. The learning curve pays off forever."],
         tasks=[I("xnet:controller"), I("xnet:connector_blue", 4)],
         rewards=[LV(5), XP(100)]),
    dict(n=6, title="Generator Coil", icon="create_new_age:generator_coil", x=3.0, y=1.5,
         sub="Big spin energy.", deps=[2], optional=True, shape="diamond",
         desc=["Create: New Age generators scale with your shaft network: build a generator from coils and magnets for serious FE output.",
               "A large setup outperforms stacks of small generators."],
         tasks=[I("create_new_age:generator_coil")],
         rewards=[R("minecraft:redstone_block", 4), XP(150)]),
    dict(n=7, title="Here Comes the Sun", icon="mekanismgenerators:solar_generator", x=4.5, y=1.5,
         sub="Photovoltaic and proud.", deps=[3], optional=True, shape="diamond",
         desc=["Mekanism Solar Generators produce clean passive power all day.",
               "Pro tip: this world has seasons — output varies. Wind power works at night too."],
         tasks=[I("mekanismgenerators:solar_generator")],
         rewards=[R("minecraft:gold_ingot", 8), XP(125)]),
    dict(n=8, title="Gone with the Wind", icon="mekanismgenerators:wind_generator", x=6.0, y=1.5,
         sub="Higher is better. Y=512 exists.", deps=[3], optional=True, shape="diamond",
         desc=["Wind Generators scale output with altitude. This world's peaks reach Y=512.",
               "Build a turbine farm on a Tectonic mega-mountain and laugh at fuel costs forever."],
         tasks=[I("mekanismgenerators:wind_generator")],
         rewards=[LV(8), XP(100)]),
])

# ── t3_ae2 ───────────────────────────────────────────────────────────────────
register_chapter("t3_ae2", 0x42000, T3, 1, "Going Digital", "ae2:controller", [
    dict(n=1, title="Certus Quartz", icon="ae2:certus_quartz_crystal", x=0.0, y=0.0,
         sub="The crystal that started it all.",
         deps=[("t3_power", 4)],
         desc=["Applied Energistics 2 stores your items as DATA. First ingredient: Certus Quartz from meteorites and underground budding blocks.",
               "Grow more from Certus Seeds in water — Growth Accelerators speed it up."],
         tasks=[I("ae2:certus_quartz_crystal", 16)],
         rewards=[R("ae2:certus_quartz_seed", 8), XP(150)]),
    dict(n=2, title="Fluix Fusion", icon="ae2:fluix_crystal", x=1.5, y=0.0,
         sub="Drop. Zap. Crystal.", deps=[1],
         desc=["Throw Charged Certus, Redstone and Quartz into water — they fuse into Fluix Crystal, AE2's core material.",
               "Charge Certus in the Charger powered by your shiny new FE network."],
         tasks=[I("ae2:fluix_crystal", 16)],
         rewards=[R("ae2:fluix_crystal", 16), XP(150)]),
    dict(n=3, title="The Inscriber", icon="ae2:inscriber", x=3.0, y=0.0,
         sub="Silicon Valley, block form.", deps=[2],
         desc=["The Inscriber stamps processors using Presses found in meteorites — Explorer's Compass can locate those!",
               "You need Silicon, Logic, Calculation and Engineering presses for the full set."],
         tasks=[I("ae2:inscriber")],
         rewards=[R("minecraft:quartz", 16), XP(150)]),
    dict(n=4, title="Processors", icon="ae2:engineering_processor", x=4.5, y=0.0,
         sub="Tiny brains for big networks.", deps=[3],
         desc=["Stamp gold for Logic, Certus for Calculation, Diamond for Engineering processors.",
               "Automate the Inscriber chain with belts or XNet — you will need processors forever."],
         tasks=[I("ae2:engineering_processor", 4)],
         rewards=[R("minecraft:diamond", 4), XP(175)]),
    dict(n=5, title="ME Controller", icon="ae2:controller", x=6.0, y=0.0,
         sub="The brain awakens.", deps=[4],
         desc=["The Controller is the heart of your ME network, providing channels through its faces.",
               "Power it, cable it, and prepare for the storage revolution."],
         tasks=[I("ae2:controller")],
         rewards=[R("ae2:fluix_glass_cable", 16), XP(200)]),
    dict(n=6, title="Your First ME Network", icon="ae2:terminal", x=7.5, y=0.0,
         sub="Goodbye, chest monster.", deps=[5],
         desc=["Connect a Terminal, an ME Drive and a storage cell: all your items, searchable, in one screen.",
               "Type @create in the terminal search to filter by mod. Your chest wall is officially obsolete."],
         tasks=[I("ae2:terminal"), I("ae2:drive"), I("ae2:item_storage_cell_4k", 2)],
         rewards=[R("ae2:item_storage_cell_16k"), LV(5)]),
    dict(n=7, title="Autocrafting", icon="ae2:pattern_provider", x=9.0, y=0.0,
         sub="Request. Receive. Repeat.", deps=[6],
         desc=["Encode recipes into Patterns, give them to Pattern Providers with Molecular Assemblers, and the network crafts ON DEMAND.",
               "This is the single biggest quality-of-life jump in the entire pack."],
         tasks=[I("ae2:pattern_provider"), I("ae2:molecular_assembler", 2), I("ae2:blank_pattern", 8)],
         rewards=[R("ae2:blank_pattern", 16), LV(10)]),
    dict(n=8, title="Crafting Terminal", icon="ae2:crafting_terminal", x=7.5, y=1.5,
         sub="A crafting table with infinite pockets.", deps=[6], optional=True, shape="diamond",
         desc=["The Crafting Terminal combines a crafting grid with full network access — craft straight from storage."],
         tasks=[I("ae2:crafting_terminal")],
         rewards=[R("minecraft:crafting_table", 1), XP(125)]),
    dict(n=9, title="Grow Op", icon="ae2:growth_accelerator", x=1.5, y=1.5,
         sub="Crystals on a schedule.", deps=[2], optional=True, shape="diamond",
         desc=["Growth Accelerators make crystal seeds mature in seconds instead of hours.",
               "Build a small crystal farm — Certus and Fluix demand never stops."],
         tasks=[I("ae2:growth_accelerator", 2)],
         rewards=[R("ae2:certus_quartz_seed", 16), XP(150)]),
    dict(n=10, title="Wireless Freedom", icon="ae2:wireless_terminal", x=9.0, y=1.5,
         sub="Your base, in your pocket.", deps=[7], optional=True, shape="diamond",
         desc=["The Wireless Terminal accesses your network from anywhere in range of a Wireless Access Point.",
               "Build it once, never walk back to the terminal room again."],
         tasks=[I("ae2:wireless_terminal")],
         rewards=[LV(8), XP(100)]),
])

# ── t3_pnc ───────────────────────────────────────────────────────────────────
register_chapter("t3_pnc", 0x43000, T3, 2, "Under Pressure", "pneumaticcraft:air_compressor", [
    dict(n=1, title="Compressed Iron", icon="pneumaticcraft:compressed_iron_ingot", x=0.0, y=0.0,
         sub="Percussive metallurgy.",
         deps=[("t2_mekanism", 4)],
         desc=["PneumaticCraft runs on AIR pressure. First, make Compressed Iron — drop iron and ignite TNT next to it. Boom, science!",
               "Wear protective gear or stand back. Preferably both."],
         tasks=[I("pneumaticcraft:compressed_iron_ingot", 8)],
         rewards=[R("minecraft:tnt", 8), XP(150)]),
    dict(n=2, title="Air Compressor", icon="pneumaticcraft:air_compressor", x=1.5, y=0.0,
         sub="It blows. Productively.", deps=[1],
         desc=["The Air Compressor burns fuel to build pressure. Connect Pressure Tubes to move air to machines.",
               "Watch the gauge: too much pressure means EXPLOSIONS. Security Upgrades are not optional. Well, they are. But shouldn't be."],
         tasks=[I("pneumaticcraft:air_compressor"), I("pneumaticcraft:pressure_tube", 8)],
         rewards=[R("pneumaticcraft:compressed_iron_ingot", 8), XP(150)]),
    dict(n=3, title="Pressure Chamber", icon="pneumaticcraft:pressure_chamber_wall", x=3.0, y=0.0,
         sub="The angry crafting cube.", deps=[2],
         desc=["Build a hollow cube of Pressure Chamber Walls with a Valve and Interface. Items inside get pressure-crafted.",
               "This makes more Compressed Iron WITHOUT explosions — and unlocks our custom enchanting tiers later!"],
         tasks=[I("pneumaticcraft:pressure_chamber_wall", 16),
                I("pneumaticcraft:pressure_chamber_valve"),
                I("pneumaticcraft:pressure_chamber_interface", 2)],
         rewards=[R("pneumaticcraft:compressed_iron_block", 2), LV(5)]),
    dict(n=4, title="Vortex of Cool", icon="pneumaticcraft:vortex_tube", x=3.0, y=1.5,
         sub="Hot side hot, cold side cold.", deps=[2], optional=True, shape="diamond",
         desc=["The Vortex Tube splits compressed air into a hot and a cold side — needed for temperature-sensitive machines.",
               "PneumaticCraft cares about heat. The Vortex Tube is your thermostat."],
         tasks=[I("pneumaticcraft:vortex_tube")],
         rewards=[R("minecraft:blue_ice", 8), XP(125)]),
    dict(n=5, title="Sky Shopping", icon="pneumaticcraft:amadron_tablet", x=1.5, y=1.5,
         sub="Drone delivery, literally.", deps=[2], optional=True, shape="diamond",
         desc=["The Amadron Tablet is a drone-powered marketplace: order goods, pay resources, get air-dropped deliveries.",
               "Some offers are absolute steals. Window-shop regularly."],
         tasks=[I("pneumaticcraft:amadron_tablet")],
         rewards=[R("minecraft:emerald", 12), XP(150)]),
])

# ── t3_ma ────────────────────────────────────────────────────────────────────
register_chapter("t3_ma", 0x44000, T3, 3, "Mystical Farming", "mysticalagriculture:inferium_essence", [
    dict(n=1, title="Prosperity", icon="mysticalagriculture:prosperity_shard", x=0.0, y=0.0,
         sub="Rocks of pure potential.",
         deps=[("t1_survival", 7)],
         desc=["Mystical Agriculture lets you GROW resources. Prosperity Shards come from prosperity ore underground.",
               "These shards build your seed infrastructure — mine generously."],
         tasks=[I("mysticalagriculture:prosperity_shard", 8)],
         rewards=[R("mysticalagriculture:prosperity_shard", 8), XP(100)]),
    dict(n=2, title="Inferium", icon="mysticalagriculture:inferium_essence", x=1.5, y=0.0,
         sub="Essence of everything.", deps=[1],
         desc=["Inferium Essence drops from mobs and inferium ore — but the real play is growing it with Inferium Seeds.",
               "It upgrades through five essence tiers: Inferium, Prudentium, Tertium, Imperium, Supremium."],
         tasks=[I("mysticalagriculture:inferium_essence", 32), I("mysticalagriculture:inferium_seeds")],
         rewards=[R("mysticalagriculture:inferium_seeds", 2), XP(125)]),
    dict(n=3, title="Infusion Altar", icon="mysticalagriculture:infusion_altar", x=3.0, y=0.0,
         sub="Stonehenge, but useful.", deps=[2],
         desc=["The Infusion Altar with eight Pedestals crafts the higher-tier seeds.",
               "Build it in the open — it needs line of sight to work its magic."],
         tasks=[I("mysticalagriculture:infusion_altar"), I("mysticalagriculture:infusion_pedestal", 8)],
         rewards=[R("mysticalagriculture:inferium_essence", 32), XP(175)]),
    dict(n=4, title="Tier 2 Seeds", icon="mysticalagriculture:iron_seeds", x=4.5, y=0.0,
         sub="Iron grows on trees now. Well, stalks.", deps=[3],
         desc=["Craft your first metal seed — iron or coal are great starters.",
               "Plant on farmland; Rich Soil from Farmer's Delight makes them grow faster!",
               "Heads up: Tier 3 seeds (diamond, emerald, gold) need a Resource Catalyst. That story continues in Tier 4."],
         tasks=[I("mysticalagriculture:iron_seeds")],
         rewards=[R("mysticalagriculture:prudentium_essence", 8), LV(5)]),
    dict(n=5, title="Seed Reprocessor", icon="mysticalagriculture:seed_reprocessor", x=4.5, y=1.5,
         sub="Recycle your botany.", deps=[3], optional=True, shape="diamond",
         desc=["The Seed Reprocessor turns unwanted seeds back into essence. Nothing wasted.",
               "Great when your farm outgrows its old seed tiers."],
         tasks=[I("mysticalagriculture:seed_reprocessor")],
         rewards=[R("mysticalagriculture:inferium_essence", 64), XP(150)]),
])

# ── t3_magic ─────────────────────────────────────────────────────────────────
register_chapter("t3_magic", 0x45000, T3, 4, "School of Magic", "ars_nouveau:worn_notebook", [
    dict(n=1, title="The Worn Notebook", icon="ars_nouveau:worn_notebook", x=0.0, y=0.0,
         sub="Required reading.",
         deps=[("t1_survival", 8)],
         desc=["Ars Nouveau begins with the Worn Notebook — your in-game guide to everything magical.",
               "Craft it with a book and lapis, and start reading."],
         tasks=[I("ars_nouveau:worn_notebook")],
         rewards=[R("minecraft:lapis_lazuli", 16), XP(100)]),
    dict(n=2, title="Novice Spellbook", icon="ars_nouveau:novice_spell_book", x=1.5, y=0.0,
         sub="Abracadabra, professionally.", deps=[1],
         desc=["The Novice Spell Book lets you craft custom spells from glyphs: Projectile-Harm, Break, Light — you design them.",
               "Create glyphs at the Scribes Table using XP and items."],
         tasks=[I("ars_nouveau:novice_spell_book"), I("ars_nouveau:scribes_table")],
         rewards=[LV(5), XP(100)]),
    dict(n=3, title="Source of Power", icon="ars_nouveau:source_jar", x=3.0, y=0.0,
         sub="Mana, but artisanal.", deps=[2],
         desc=["Magical machines need Source. The Agronomic Sourcelink generates it from growing crops nearby.",
               "Store it in Source Jars next to your magical workstations."],
         tasks=[I("ars_nouveau:source_jar", 2), I("ars_nouveau:agronomic_sourcelink")],
         rewards=[R("ars_nouveau:source_gem", 8), XP(150)]),
    dict(n=4, title="Imbuement Chamber", icon="ars_nouveau:imbuement_chamber", x=4.5, y=0.0,
         sub="Lapis goes in. Magic comes out.", deps=[3],
         desc=["The Imbuement Chamber converts lapis and amethyst into Source Gems — the magical crafting material.",
               "It draws from nearby Source Jars automatically."],
         tasks=[I("ars_nouveau:imbuement_chamber")],
         rewards=[R("ars_nouveau:source_gem", 8), XP(150)]),
    dict(n=5, title="Enchanting Apparatus", icon="ars_nouveau:enchanting_apparatus", x=6.0, y=0.0,
         sub="The magical multitool.", deps=[4],
         desc=["The Enchanting Apparatus with Arcane Pedestals crafts all advanced Ars gear: armor, charms, and the next spellbook tiers."],
         tasks=[I("ars_nouveau:enchanting_apparatus")],
         rewards=[R("ars_nouveau:source_gem", 12), XP(175)]),
    dict(n=6, title="Apprentice Graduation", icon="ars_nouveau:apprentice_spell_book", x=7.5, y=0.0,
         sub="Now with 100% more glyph slots.", deps=[5],
         desc=["Upgrade to the Apprentice Spell Book for stronger spells and more mana.",
               "The Archmage tier awaits in Tier 4 — with Drygmys that farm bosses for you."],
         tasks=[I("ars_nouveau:apprentice_spell_book")],
         rewards=[LV(10), XP(150)]),
    dict(n=7, title="Starbuncle Express", icon="ars_nouveau:starbuncle_charm", x=4.5, y=1.5,
         sub="Gold-powered gremlin logistics.", deps=[4], optional=True, shape="diamond",
         desc=["Starbuncles transport items between inventories — pay them in gold nuggets.",
               "They're adorable, slightly chaotic and surprisingly efficient."],
         tasks=[I("ars_nouveau:starbuncle_charm")],
         rewards=[R("minecraft:gold_ingot", 16), XP(150)]),
    dict(n=8, title="Scrolls of Power", icon="minecraft:writable_book", x=1.5, y=1.5,
         sub="Fireball goes whoosh.", deps=[2], optional=True, shape="diamond",
         desc=["Iron's Spells 'n Spellbooks adds a second magic system: find spell scrolls in dungeons and inscribe them into spellbooks.",
               "Lightning, fire, evocation — collect rare scrolls from structures and bosses."],
         tasks=[CK("Find an Iron's Spellbooks scroll")],
         rewards=[R("minecraft:diamond", 6), LV(5)]),
    dict(n=9, title="Deal with the Devil", icon="minecraft:soul_lantern", x=3.0, y=1.5,
         sub="Summoning spirits for fun and profit.", deps=[3], optional=True, shape="diamond",
         desc=["Occultism lets you summon spirits for storage, mining and crafting. Start with the Dictionary of Spirits.",
               "Its Storage Actuator is a whole dimensional storage system — a dark-arts alternative to AE2."],
         tasks=[I("occultism:dictionary_of_spirits")],
         rewards=[R("minecraft:soul_sand", 16), R("minecraft:diamond", 4), XP(175)]),
])
