"""Tier 4 chapters: heavy Mekanism, MEGA storage, catalyst system, magical automation, enchanting."""
from lib import register_chapter, I, K, CK, R, XP, LV

T4 = 0x50000

# ── t4_mekanism ──────────────────────────────────────────────────────────────
register_chapter("t4_mekanism", 0x51000, T4, 0, "Heavy Industry", "mekanism:purification_chamber", [
    dict(n=1, title="Purification Chamber", icon="mekanism:purification_chamber", x=0.0, y=0.0,
         sub="Now with 50% more ore.",
         deps=[("t3_ae2", 7), ("t3_power", 5)],
         desc=["The Purification Chamber uses oxygen to turn raw ore into THREE clumps instead of two dusts.",
               "Feed it oxygen from an Electrolytic Separator splitting water. Welcome to x3 ore processing."],
         tasks=[I("mekanism:purification_chamber")],
         rewards=[R("mekanism:advanced_control_circuit", 4), XP(200)]),
    dict(n=2, title="The x3 Ore Chain", icon="mekanism:dust_osmium", x=1.5, y=0.0,
         sub="Clump. Shard. Dust. Ingot. Profit.", deps=[1],
         desc=["Full chain: Purification Chamber makes clumps, Crusher makes dirty dust, Enrichment Chamber cleans it, smelt to ingots.",
               "Automate it with XNet or AE2 and never think about ores again."],
         tasks=[I("mekanism:crusher"), I("mekanism:dust_osmium", 48)],
         rewards=[R("minecraft:raw_gold", 32), R("minecraft:raw_iron", 32), XP(200)]),
    dict(n=3, title="Advanced Alloys", icon="mekanism:alloy_atomic", x=3.0, y=0.0,
         sub="The good stuff.", deps=[2],
         desc=["Reinforced Alloy needs diamond infusion, Atomic Alloy needs Refined Obsidian.",
               "These alloys gate Mekanism's endgame: the Digital Miner, teleporters and the Fusion Reactor."],
         tasks=[I("mekanism:alloy_reinforced", 8), I("mekanism:alloy_atomic", 4)],
         rewards=[LV(10), XP(150)]),
    dict(n=4, title="Refined Obsidian", icon="mekanism:ingot_refined_obsidian", x=4.5, y=0.0,
         sub="Obsidian, but it lifts.", deps=[3],
         desc=["Refined Obsidian is one of the strongest materials in the game.",
               "You will need it for atomic alloys — and for our custom Refined Obsidian Drill Head."],
         tasks=[I("mekanism:ingot_refined_obsidian", 8)],
         rewards=[R("mekanism:ingot_refined_glowstone", 8), XP(200)]),
    dict(n=5, title="Personal Flight", icon="mekanism:jetpack", x=1.5, y=1.5,
         sub="OSHA has left the chat.", deps=[2], optional=True, shape="diamond",
         desc=["The Mekanism Jetpack runs on hydrogen from an Electrolytic Separator.",
               "Hover mode (toggle with a keybind) makes building megastructures painless. A worthy detour."],
         tasks=[I("mekanism:jetpack")],
         rewards=[LV(10), XP(150)]),
    dict(n=6, title="Atomic Disassembler", icon="mekanism:atomic_disassembler", x=3.0, y=1.5,
         sub="The drill that ate a sword.", deps=[3], optional=True, shape="diamond",
         desc=["One tool to replace them all: pickaxe, shovel, axe, sword and hoe — with adjustable speed modes.",
               "Vein mode plus FTB Ultimine equals geological war crimes."],
         tasks=[I("mekanism:atomic_disassembler")],
         rewards=[R("minecraft:diamond_block", 2), LV(8)]),
    dict(n=7, title="Chemistry Lab", icon="mekanism:chemical_oxidizer", x=4.5, y=1.5,
         sub="x4 is calling.", deps=[4], optional=True, shape="diamond",
         desc=["The Chemical Oxidizer and Washer prepare hydrogen chloride for x4 ore processing via the Chemical Injection Chamber.",
               "The rabbit hole goes deep — and the yields go up."],
         tasks=[I("mekanism:chemical_oxidizer"), I("mekanism:chemical_washer")],
         rewards=[R("minecraft:diamond", 8), LV(8)]),
])

# ── t4_ae2_mega ──────────────────────────────────────────────────────────────
register_chapter("t4_ae2_mega", 0x52000, T4, 1, "Mass Storage", "megacells:item_storage_cell_64m", [
    dict(n=1, title="Drive Array", icon="ae2:drive", x=0.0, y=0.0,
         sub="RAID, Minecraft edition.",
         deps=[("t3_ae2", 7)],
         desc=["Scale up your network: multiple ME Drives with bigger cells.",
               "Pro tip: partition cells per item type so bulk items don't clog your fancy storage."],
         tasks=[I("ae2:drive", 2), I("ae2:item_storage_cell_64k", 2)],
         rewards=[R("ae2:item_storage_cell_256k"), XP(200)]),
    dict(n=2, title="Enter MEGA", icon="megacells:item_storage_cell_1m", x=1.5, y=0.0,
         sub="Storage with a gym membership.", deps=[1],
         desc=["MEGA Cells extends AE2 with cells from 1M up to a ludicrous 256M items.",
               "Built from Sky Steel — found in meteorites or crafted."],
         tasks=[I("megacells:item_storage_cell_1m")],
         rewards=[R("megacells:item_storage_cell_4m"), LV(10)]),
    dict(n=3, title="64M — Practically Infinite", icon="megacells:item_storage_cell_64m", x=3.0, y=0.0,
         sub="Hoarding, but make it digital.", deps=[2],
         desc=["A single 64M cell holds more than 1000 double chests.",
               "At this point your storage problem is officially a rounding error."],
         tasks=[I("megacells:item_storage_cell_64m")],
         rewards=[R("megacells:cell_component_64m"), LV(15)]),
    dict(n=4, title="Quantum Bridge", icon="ae2:quantum_ring", x=1.5, y=1.5,
         sub="Your network. Everywhere. Yes, even there.", deps=[1], optional=True, shape="diamond",
         desc=["Quantum Network Bridges link ME networks across ANY distance — even across dimensions.",
               "Mining outpost in the Nether, main base at home: one seamless network."],
         tasks=[I("ae2:quantum_ring", 8)],
         rewards=[R("ae2:quantum_entangled_singularity", 2), LV(10)]),
])

# ── t4_catalyst ──────────────────────────────────────────────────────────────
register_chapter("t4_catalyst", 0x53000, T4, 2, "The Catalyst", "gaia:resource_catalyst", [
    dict(n=1, title="Resource Catalyst", icon="gaia:resource_catalyst", x=0.0, y=0.0,
         sub="The key to growing the un-growable.",
         deps=[("t3_ma", 4), ("t2_create_brass", 5)],
         desc=["Tier 3 seeds (diamond, emerald, gold, glowstone) need the Resource Catalyst. Three ways to get one:",
               "1. PASSIVE: rare drop from Create Ore Excavation veins.",
               "2. CRAFT: Mechanical Crafter recipe with essences and an Apotheosis gem.",
               "3. ALTAR: fill a Catalyst Altar with Hyper Experience using a Create Spout."],
         tasks=[I("gaia:resource_catalyst")],
         rewards=[R("mysticalagriculture:inferium_essence", 64), LV(10)]),
    dict(n=2, title="Tier 3 Seeds", icon="mysticalagriculture:diamond_seeds", x=1.5, y=0.0,
         sub="Diamonds. On stalks.", deps=[1],
         desc=["With a Resource Catalyst in hand, craft a Tier 3 seed at last.",
               "Diamond, emerald, gold or glowstone — your farm now prints wealth."],
         tasks=[I("mysticalagriculture:diamond_seeds")],
         rewards=[R("mysticalagriculture:diamond_essence", 8), LV(10)]),
    dict(n=3, title="Vein Mining", icon="createoreexcavation:drill", x=0.0, y=1.5,
         sub="Infinite ores, finite patience.", deps=[("t2_create_brass", 6)],
         desc=["Create Ore Excavation drills tap ore veins for INFINITE resources — powered by Create rotation.",
               "Use the Vein Atlas to find veins. Drilling them can also drop Resource Catalysts!"],
         tasks=[I("createoreexcavation:drill"), I("createoreexcavation:vein_atlas")],
         rewards=[R("minecraft:raw_iron", 64), XP(200)]),
    dict(n=4, title="Osmium Drill Head", icon="gaia:osmium_drill_head", x=1.5, y=1.5,
         sub="Custom hardware for serious mining.", deps=[3],
         desc=["Our custom Drill Heads upgrade your excavation: the Osmium Drill Head speeds up vein drilling.",
               "Crafted from osmium and machine parts — the first of five tiers."],
         tasks=[I("gaia:osmium_drill_head")],
         rewards=[R("mekanism:ingot_osmium", 16), XP(200)]),
    dict(n=5, title="Obsidian Upgrade", icon="gaia:refined_obsidian_drill_head", x=3.0, y=1.5,
         sub="Drills harder. Lasts longer.", deps=[4, ("t4_mekanism", 4)],
         desc=["The Refined Obsidian Drill Head is the Tier 4 workhorse — faster veins, better catalyst chances."],
         tasks=[I("gaia:refined_obsidian_drill_head")],
         rewards=[LV(10), XP(150)]),
    dict(n=6, title="Crystal Clear", icon="gaia:crystal_drill_head", x=3.0, y=3.0,
         sub="Sparkly AND functional.", deps=[4], optional=True, shape="diamond",
         desc=["The Crystal Drill Head specializes in crystal veins — certus, amethyst, fluorite."],
         tasks=[I("gaia:crystal_drill_head")],
         rewards=[R("ae2:certus_quartz_crystal", 32), XP(175)]),
    dict(n=7, title="Hot Stuff", icon="gaia:nether_drill_head", x=1.5, y=3.0,
         sub="Rated for lava. Mostly.", deps=[4], optional=True, shape="diamond",
         desc=["The Nether Drill Head excels at Nether veins — quartz, gold, ancient debris."],
         tasks=[I("gaia:nether_drill_head")],
         rewards=[R("minecraft:netherite_scrap", 2), XP(200)]),
    dict(n=8, title="Altar of Power", icon="gaia:catalyst_altar", x=0.0, y=3.0,
         sub="XP in, catalyst out.", deps=[1], optional=True, shape="diamond",
         desc=["The Catalyst Altar converts liquid experience into catalysts: a Create Spout fills it with Hyper Experience.",
               "This is the automatable path — set it up and catalysts become renewable."],
         tasks=[I("gaia:catalyst_altar")],
         rewards=[LV(15), XP(150)]),
])

# ── t4_ars ───────────────────────────────────────────────────────────────────
register_chapter("t4_ars", 0x54000, T4, 3, "Magical Automation", "ars_nouveau:drygmy_charm", [
    dict(n=1, title="The Drygmy", icon="ars_nouveau:drygmy_charm", x=0.0, y=0.0,
         sub="Mossy little loot goblin.",
         deps=[("t3_magic", 6)],
         desc=["Drygmys channel nearby mobs to produce their drops WITHOUT killing them.",
               "Yes, that includes bosses. Let that sink in."],
         tasks=[I("ars_nouveau:drygmy_charm")],
         rewards=[R("ars_nouveau:source_gem", 16), XP(200)]),
    dict(n=2, title="Drygmy Farm", icon="minecraft:moss_block", x=1.5, y=0.0,
         sub="The boss farm of legend.", deps=[1],
         desc=["Build a Drygmy enclosure with captured mobs and a steady Source supply.",
               "Capture a Cataclysm boss with this setup later and it will generate Mythic Catalyst materials for Tier 5!"],
         tasks=[CK("Build a working Drygmy farm")],
         rewards=[R("minecraft:diamond_block", 2), LV(15)]),
    dict(n=3, title="Archmage", icon="ars_nouveau:archmage_spell_book", x=3.0, y=0.0,
         sub="Final form: paperwork wizard.", deps=[1],
         desc=["The Archmage Spell Book is the highest tier — maximum mana, maximum glyph slots.",
               "Your spells are now limited only by imagination and source supply."],
         tasks=[I("ars_nouveau:archmage_spell_book")],
         rewards=[LV(20), XP(200)]),
    dict(n=4, title="Whirlisprig Gardens", icon="ars_nouveau:whirlisprig_charm", x=1.5, y=1.5,
         sub="Botanical workforce.", deps=[1], optional=True, shape="diamond",
         desc=["Whirlisprigs harvest and replant crops around them — a fully magical farm.",
               "Pair with your Mystical Agriculture fields for hands-free essence."],
         tasks=[I("ars_nouveau:whirlisprig_charm")],
         rewards=[R("mysticalagriculture:prudentium_essence", 16), XP(175)]),
    dict(n=5, title="Wixie's Workshop", icon="ars_nouveau:wixie_charm", x=3.0, y=1.5,
         sub="Potion brewing, outsourced.", deps=[3], optional=True, shape="diamond",
         desc=["Wixies craft items and brew potions from materials in nearby containers.",
               "A magical alternative to autocrafting — with more attitude."],
         tasks=[I("ars_nouveau:wixie_charm")],
         rewards=[R("minecraft:blaze_powder", 16), XP(175)]),
])

# ── t4_enchant ───────────────────────────────────────────────────────────────
register_chapter("t4_enchant", 0x55000, T4, 4, "Beyond Vanilla Enchanting", "minecraft:enchanting_table", [
    dict(n=1, title="Gem Hunter", icon="apotheosis:gem", x=0.0, y=0.0,
         sub="Mobs drop jewelry now.",
         deps=[("t3_pnc", 3)],
         desc=["Apotheosis gems drop from monsters — each carries stat bonuses based on rarity.",
               "Socket them into gear at a Smithing Table. Collect, compare, combine."],
         tasks=[I("apotheosis:gem", 3)],
         rewards=[R("apotheosis:gem_dust", 8), XP(200)]),
    dict(n=2, title="Socket to Me", icon="minecraft:smithing_table", x=1.5, y=0.0,
         sub="Gear with extra steps. Worth it.", deps=[1],
         desc=["Use a Sigil of Socketing to add gem sockets to your gear, then slot in your best gems.",
               "Higher rarity gems give absurd bonuses — Mythic gems can double your damage."],
         tasks=[CK("Socket a gem into your gear")],
         rewards=[LV(10), XP(150)]),
    dict(n=3, title="Liquid Knowledge", icon="create_enchantment_industry:experience_rotor", x=3.0, y=0.0,
         sub="XP. In a pipe. What a time to be alive.", deps=[2],
         desc=["Create: Enchantment Industry turns experience into a FLUID. The Experience Rotor harvests it from belts of items.",
               "Condense regular XP into Hyper Experience — fuel for the Catalyst Altar and high-tier enchanting."],
         tasks=[I("create_enchantment_industry:experience_rotor")],
         rewards=[R("minecraft:experience_bottle", 32), XP(200)]),
    dict(n=4, title="Pressure Enchanting", icon="pneumaticcraft:pressure_chamber_valve", x=4.5, y=0.0,
         sub="Enchantments past the legal limit.", deps=[3],
         desc=["Our custom system: the PneumaticCraft Pressure Chamber pushes enchantments BEYOND vanilla caps.",
               "Higher pressure tiers (3.5, 5.5, 7.5 bar) unlock enchantment levels up to GODLIKE. Check the Enchantment Library to store and combine."],
         tasks=[CK("Use the pressure enchanting system")],
         rewards=[LV(15), XP(200)]),
])
