"""Tier 5 chapters: apex bosses and endgame."""
from lib import register_chapter, I, K, CK, R, XP, LV

T5 = 0x60000

# ── t5_bosses ────────────────────────────────────────────────────────────────
register_chapter("t5_bosses", 0x61000, T5, 0, "Apex Predators", "minecraft:wither_skeleton_skull", [
    dict(n=1, title="Ready for Tier 5", icon="minecraft:netherite_chestplate", x=0.0, y=0.0,
         sub="Gear check. This is not a drill.", shape="gear",
         deps=[("t4_mekanism", 3), ("t4_ae2_mega", 3), ("t4_ars", 2)],
         desc=["Beyond this point lie the Cataclysm Apex bosses — the hardest fights in the pack.",
               "Recommended: socketed gear, high-tier enchantments, buff foods, a respawn plan and friends who owe you favors."],
         tasks=[CK("I am prepared. Probably.")],
         rewards=[R("minecraft:golden_apple", 8), LV(10)]),
    dict(n=2, title="Netherite Monstrosity", icon="minecraft:netherite_ingot", x=1.5, y=0.0,
         sub="A wall of angry metal.", deps=[1],
         desc=["The Netherite Monstrosity lurks in Cataclysm's Soul Black Smith dungeons.",
               "It hits like a meteor and summons lava. Ranged attacks and fire resistance are your friends."],
         tasks=[K("cataclysm:netherite_monstrosity")],
         rewards=[R("minecraft:netherite_ingot", 2), LV(15)]),
    dict(n=3, title="Ignis, Lord of Fire", icon="minecraft:blaze_powder", x=3.0, y=0.0,
         sub="The floor is literally lava.", deps=[2],
         desc=["Ignis awaits in the Burning Arena — a duelist with phases, shields and flame combos.",
               "Learn the patterns. Respect the sword. Loot the legend."],
         tasks=[K("cataclysm:ignis")],
         rewards=[R("minecraft:netherite_scrap", 4), LV(20)]),
    dict(n=4, title="The Harbinger", icon="minecraft:redstone_block", x=4.5, y=0.0,
         sub="Laser-guided doom machine.", deps=[3],
         desc=["The Harbinger hovers in Ruined Citadels: lasers, missiles, death from above.",
               "Bring ranged weapons and cover. Its remains build powerful tech gear."],
         tasks=[K("cataclysm:the_harbinger")],
         rewards=[R("minecraft:diamond_block", 3), LV(20)]),
    dict(n=5, title="Ender Guardian", icon="minecraft:ender_eye", x=6.0, y=0.0,
         sub="The End's final boss. The dragon was the tutorial.", deps=[4],
         desc=["Deep in the Ruined Fortress of the End, the Ender Guardian punches reality itself.",
               "Gravity attacks, teleport punishes, arena control. The ultimate melee test."],
         tasks=[K("cataclysm:ender_guardian")],
         rewards=[R("minecraft:nether_star", 2), LV(25)]),
    dict(n=6, title="Singularity Shards", icon="gaia:singularity_shard", x=3.0, y=1.5,
         sub="Fragments of compressed victory.", deps=[2],
         desc=["Apex bosses drop Singularity Shards — the key ingredient for Mythic Liquid XP.",
               "Your Drygmy farm can generate these passively from a captured boss. Automation beats heroism."],
         tasks=[I("gaia:singularity_shard", 4)],
         rewards=[LV(15), XP(200)]),
    dict(n=7, title="Mythic Catalyst", icon="gaia:mythic_catalyst", x=4.5, y=1.5,
         sub="The rarest of keys.", deps=[6],
         desc=["The Mythic Catalyst gates Tier 4 seeds: craft it at the Catalyst Altar with Mythic Liquid XP, or claim it from Apex bosses.",
               "Either way, you earned this."],
         tasks=[I("gaia:mythic_catalyst")],
         rewards=[R("mysticalagriculture:prudentium_essence", 32), LV(20)]),
    dict(n=8, title="The Wither", icon="minecraft:wither_skeleton_skull", x=1.5, y=-1.5,
         sub="A classic. Still rude.", deps=[1], optional=True, shape="diamond",
         desc=["The vanilla Wither — almost quaint by this pack's standards, but nether stars power beacons and high-tier crafts."],
         tasks=[K("minecraft:wither")],
         rewards=[R("minecraft:diamond_block", 2), LV(10)]),
    dict(n=9, title="The Warden", icon="minecraft:sculk_shrieker", x=3.0, y=-1.5,
         sub="Shhhhhh.", deps=[1], optional=True, shape="diamond",
         desc=["Killing the Warden is strictly optional and widely considered a bad idea.",
               "Which is exactly why there's a reward for it."],
         tasks=[K("minecraft:warden")],
         rewards=[R("minecraft:diamond_block", 4), LV(20)]),
])

# ── t5_endgame ───────────────────────────────────────────────────────────────
register_chapter("t5_endgame", 0x62000, T5, 1, "Gaia Awakens", "gaia:gaia_awakening_token", [
    dict(n=1, title="Tier 4 Seeds", icon="mysticalagriculture:osmium_seeds", x=0.0, y=0.0,
         sub="Growing the periodic table.",
         deps=[("t5_bosses", 7)],
         desc=["With Mythic Catalysts you can craft Tier 4 seeds: osmium, tin, lead, uranium, fluorite.",
               "Your farm now supplies your entire industry."],
         tasks=[I("mysticalagriculture:osmium_seeds")],
         rewards=[R("mysticalagriculture:prudentium_essence", 32), LV(15)]),
    dict(n=2, title="Mythic Liquid XP", icon="gaia:mythic_xp_shard", x=1.5, y=0.0,
         sub="Experience, distilled to perfection.", deps=[("t5_bosses", 6)],
         desc=["Mix Hyper Experience with a Singularity Shard in a heated Create Mixer to brew Mythic Liquid XP.",
               "Spout it onto a Catalyst Altar for renewable Mythic Catalysts. Full automation achieved."],
         tasks=[I("gaia:mythic_liquid_xp_bucket")],
         rewards=[LV(20), XP(250)]),
    dict(n=3, title="Digital Miner", icon="mekanism:digital_miner", x=0.0, y=1.5,
         sub="Mining from your armchair.", deps=[1],
         desc=["The Digital Miner extracts specific blocks in a huge radius — filter by ore, set silk touch, press go.",
               "The pickaxe in your hotbar is now decorative."],
         tasks=[I("mekanism:digital_miner")],
         rewards=[LV(15), XP(200)]),
    dict(n=4, title="Fusion Reactor", icon="mekanismgenerators:fusion_reactor_controller", x=1.5, y=1.5,
         sub="A small star. In your basement. Fine.", deps=[3],
         desc=["The Mekanism Fusion Reactor: laser ignition, D-T fuel, and more power than you will ever need.",
               "The endgame energy crown. Wear it proudly."],
         tasks=[I("mekanismgenerators:fusion_reactor_controller")],
         rewards=[LV(30), XP(300)]),
    dict(n=5, title="Maximum Capacity", icon="megacells:item_storage_cell_256m", x=3.0, y=1.5,
         sub="256 million. Why? Because.", deps=[4], optional=True, shape="diamond",
         desc=["The 256M MEGA cell is the largest storage in the pack. There is no practical reason. There never was.",
               "Flex responsibly."],
         tasks=[I("megacells:item_storage_cell_256m")],
         rewards=[LV(25), XP(250)]),
    dict(n=6, title="The Gaia Core", icon="gaia:gaia_core", x=3.0, y=0.0,
         sub="All paths converge.", deps=[2, 4],
         desc=["The Gaia Core unites every discipline: tech, magic, farming and conquest.",
               "Crafting it proves you have mastered this world."],
         tasks=[I("gaia:gaia_core")],
         rewards=[LV(30), XP(300)]),
    dict(n=7, title="GAIA AWAKENS", icon="gaia:gaia_awakening_token", x=4.5, y=0.5,
         sub="The world stirs. You made it happen.", deps=[6], shape="gear",
         desc=["The Gaia Awakening Token. The final craft. The end of the quest book — and the beginning of whatever you build next.",
               "Thank you for playing. Now go terrify your friends with your fusion-powered flying fortress."],
         tasks=[I("gaia:gaia_awakening_token")],
         rewards=[R("minecraft:nether_star", 3), R("minecraft:enchanted_golden_apple", 3), LV(50)]),
])
