name = "Gaia Awakening"
author = "VugasDev"
version = "0.1.27-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26d6601b1c94dfbf77c88712ab68c87c46243305ecf1244fd91c3fd5c2f4143b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
